[WIP] [feature/OA-33 => DEV] En tant qu_assistant, je voudrais que la recherche d_unités d_enseignement soit plus clair.
uclouvain/osis-assistant pull request #102
Opened 2022-06-09 12:39 UTC by sips-uclouvain

Pull request automatique de feature/OA-33 vers DEV

2022-06-09 14:45 UTC, johangirardin commented
![Capture d’écran de 2022-06-09 16-37-29](https://user-images.githubusercontent.com/12764043/172875113-622ce890-0a28-451d-b20c-d3c588503a4c.png)
Dans le form, learning unit year était exclu, à revoir ?

2022-06-13 08:46 UTC, edd19 commented on templates/tutoring_learning_unit_year.html
> +        // ?? $('#learning_unit_year_id').empty();
Ce commentaire peut-être supprimé.

2022-06-17 08:19 UTC, edd19 requested changes

2022-06-17 08:19 UTC, edd19 commented on views/autocomplete.py
> +            # qs = search(acronym=self.q)
Supprimer le commentaire

2022-06-30 09:11 UTC, merged