Add decline mandate's assistant button to the manager form
uclouvain/osis-assistant pull request #106
Opened 2022-06-29 11:55 UTC by johangirardin

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis-portal avec les changements effectués dans osis si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2022-06-29 11:57 UTC, johangirardin commented
Je n'étais pas sûr s'il fallait reprendre ce bout de code lors du changement d'état =>

                assistant = mandate.assistant
                html_template_ref = 'assistant_dean_assistant_decline_html'
                txt_template_ref = 'assistant_dean_assistant_decline_txt'
                send_message(person=faculty_dean.person, html_template_ref=html_template_ref,
                             txt_template_ref=txt_template_ref, assistant=assistant)

2022-06-29 12:33 UTC, johangirardin commented
> Je n'étais pas sûr s'il fallait reprendre ce bout de code lors du changement d'état ? =>
> 
> ```
>             assistant = mandate.assistant
>             html_template_ref = 'assistant_dean_assistant_decline_html'
>             txt_template_ref = 'assistant_dean_assistant_decline_txt'
>             send_message(person=faculty_dean.person, html_template_ref=html_template_ref,
>                          txt_template_ref=txt_template_ref, assistant=assistant)
> ```

Donc finalement je laisse tel quel bien que cela fasse 2 block de code assez similaire pour l'assistant et le manager

2022-06-30 09:16 UTC, edd19 requested changes
Ok, pour moi.
Juste les commentaires à supprimer

2022-06-30 09:16 UTC, edd19 commented on views/mandate.py
> +                # Idem => assistant = academic_assistant.find_by_person(pers)
Retirer les commentaires

2022-07-13 11:53 UTC, edd19 approved these changes

2022-07-13 11:54 UTC, merged