Python migration
uclouvain/osis-assistant pull request #162
Opened 2024-09-04 17:01 UTC by BenJneB

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis-portal avec les changements effectués dans osis si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2024-09-04 17:18 UTC, BenJneB commented
rerun unit tests

2024-09-08 14:35 UTC, BenJneB commented
tests ko => fixed with https://github.com/uclouvain/osis/pull/17143

2024-10-23 08:12 UTC, johangirardin requested changes

2024-10-23 08:14 UTC, BenJneB commented on tests/models/test_review.py
> +        self.assertQuerySetEqual(
Ca fait péter car la version de django est pas a 4 sur DEV

2024-10-23 08:20 UTC, johangirardin approved these changes

2024-11-05 15:17 UTC, merged